name: ${rootProject.name}
main: ${group}
version: ${version}
depend:
  - NyEconomy
commands:
  pokeproppond:
    description: main cmd
permissions:
  pokeproppond.cmd.reload:
    description: 重载命令
    default: op
  pokeproppond.cmd.evs:
    description: 努力点数分配权
    default: true
  pokeproppond.listener.evsgained:
    description: 取消原版努力值得到的方式
    default: true